# Generated by Django 3.0.5 on 2020-05-02 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billings.Order'),
        ),
    ]
