# Generated by Django 3.0.5 on 2020-05-24 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_remove_book_orders'),
        ('billings', '0003_order_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('book',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Book')),
                ('order',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billings.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='billings.OrderBook', to='products.Book'),
        ),
    ]
