# Generated by Django 3.0.5 on 2020-04-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
        ('products', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='billings.Order'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(null=True),
        ),
    ]
