# Generated by Django 3.0.5 on 2020-05-24 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_book_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='orders',
        ),
    ]
